<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="lap1154" failures="2" tests="5" name="Test" time="18.081" errors="0" timestamp="2023-03-08T02:55:25 IST">
  <testcase classname="com.TestCases.VerifyUserLoginTest" name="invalid_User_invalid_pass" time="0.552">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index 0 out of bounds for length 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:385)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at com.TestCases.VerifyUserLoginTest.invalid_User_invalid_pass(VerifyUserLoginTest.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- invalid_User_invalid_pass -->
  <testcase classname="com.TestCases.VerifyUserLoginTest" name="invalid_User_valid_pass" time="1.4"/>
  <testcase classname="com.TestCases.VerifyUserLoginTest" name="validUserinvalidPass" time="1.371"/>
  <testcase classname="com.TestCases.VerifyUserLoginTest" name="validUserinvalidPass" time="1.316"/>
  <testcase classname="com.TestCases.VerifyUserLoginTest" name="validUserLogin" time="1.564">
    <failure type="java.lang.AssertionError" message="expected [CHOOSE A STORE] but found [ESCOLHA UMA LOJA]">
      <![CDATA[java.lang.AssertionError: expected [CHOOSE A STORE] but found [ESCOLHA UMA LOJA]
at com.TestCases.VerifyUserLoginTest.validUserLogin(VerifyUserLoginTest.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- validUserLogin -->
</testsuite> <!-- Test -->
